"""
fastlane_manager.py — Generate Fastlane configuration files for automated
                       store deployment (Google Play and App Store Connect).
"""
from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# ── Fastfile template ─────────────────────────────────────────────────────────

_FASTFILE_TPL = """\
# Fastfile — auto-generated by app_builder.py
# Edit this file to customise your deployment lanes.

default_platform(:android)

platform :android do
  desc "Build and upload to Google Play (internal track)"
  lane :deploy_android do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android/"
    )
    upload_to_play_store(
      package_name: "{android_package}",
      track: "internal",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      json_key: "{google_play_json_key}"
    )
  end

  desc "Run Android unit tests"
  lane :test_android do
    gradle(task: "test", project_dir: "android/")
  end
end

platform :ios do
  desc "Build and upload to App Store Connect"
  lane :deploy_ios do
    build_ios_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "{export_method}",
      export_options: {{
        teamID: "{team_id}"
      }}
    )
    upload_to_app_store(
      app_identifier: "{ios_app_identifier}",
      api_key_path: "{app_store_connect_key_filepath}"
    )
  end
end
"""

_APPFILE_TPL = """\
# Appfile — auto-generated by app_builder.py

app_identifier("{ios_app_identifier}")  # iOS bundle ID
apple_id("")                             # Your Apple ID

package_name("{android_package}")       # Android package name
"""

_GEMFILE_TPL = """\
source "https://rubygems.org"

gem "fastlane"
"""


class FastlaneManager:
    """Generate Fastlane configuration for automated store deployment."""

    def __init__(self, config: dict) -> None:
        self._config = config
        self._fl_cfg: dict = config.get("fastlane", {})
        self._ios_cfg: dict = config.get("ios", {})

    # ── Public API ────────────────────────────────────────────────────────────

    def setup(self, app_path: Path) -> None:
        """Generate Fastfile, Appfile, and Gemfile in *app_path*/fastlane/.

        Skips silently if fastlane.enabled is False.
        """
        if not self._fl_cfg.get("enabled", False):
            logger.info("Fastlane disabled in config — skipping")
            return

        logger.info("Setting up Fastlane …")
        fl_dir = app_path / "fastlane"
        fl_dir.mkdir(exist_ok=True)

        self._write_fastfile(fl_dir)
        self._write_appfile(fl_dir)
        self._write_gemfile(app_path)

        logger.info("  Fastlane setup complete → %s", fl_dir)

    # ── Private helpers ───────────────────────────────────────────────────────

    def _write_fastfile(self, fl_dir: Path) -> None:
        content = _FASTFILE_TPL.format(
            android_package=self._fl_cfg.get("android_package", "com.example.app"),
            google_play_json_key=self._fl_cfg.get("google_play_json_key", ""),
            ios_app_identifier=self._fl_cfg.get("ios_app_identifier", "com.example.app"),
            export_method=self._ios_cfg.get("export_method", "app-store"),
            team_id=self._ios_cfg.get("team_id", ""),
            app_store_connect_key_filepath=self._fl_cfg.get("app_store_connect_key_filepath", ""),
        )
        (fl_dir / "Fastfile").write_text(content, encoding="utf-8")
        logger.info("  Fastfile written")

    def _write_appfile(self, fl_dir: Path) -> None:
        content = _APPFILE_TPL.format(
            ios_app_identifier=self._fl_cfg.get("ios_app_identifier", "com.example.app"),
            android_package=self._fl_cfg.get("android_package", "com.example.app"),
        )
        (fl_dir / "Appfile").write_text(content, encoding="utf-8")
        logger.info("  Appfile written")

    def _write_gemfile(self, app_path: Path) -> None:
        gemfile = app_path / "Gemfile"
        if not gemfile.exists():
            gemfile.write_text(_GEMFILE_TPL, encoding="utf-8")
            logger.info("  Gemfile written → %s", gemfile)
